# Generated by Django 5.0.4 on 2024-04-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=255)),
                ('projectCreated', models.DateTimeField(auto_now=True)),
                ('members', models.JSONField(null=True)),
                ('task', models.JSONField(null=True)),
            ],
        ),
    ]
