# Generated by Django 5.0.4 on 2024-04-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colony', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='task',
            field=models.JSONField(null=True),
        ),
    ]
