# Generated by Django 5.0.4 on 2024-05-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Colony', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='task',
        ),
    ]
