# Generated by Django 5.0.4 on 2024-05-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colony', '0003_remove_project_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
