# Generated by Django 5.0.4 on 2024-05-17 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colony', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='receiver',
        ),
        migrations.AddField(
            model_name='comment',
            name='reciever',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='leader',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Colony.project'),
        ),
    ]
