# Generated by Django 5.0.4 on 2024-04-15 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Colony', '0002_initial'),
        ('invitations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invitation_reciever', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invite',
            name='invitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invitation_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invite',
            name='projectname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Colony.project'),
        ),
    ]
