# Generated by Django 5.0.4 on 2024-05-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='projectname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
